WebApplication4/Models/Post.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace WebApplication4.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreatedTime { get; set; }
        public IdentityUser Author { get; set; }
        public int TopicId { get; set; }
        public Topic Topic { get; set; }
        public ICollection<Reply> Replies { get; set; }
    }
}

WebApplication4/ViewModels/PostViewModel.cs
using System;
using System.Collections.Generic;
using WebApplication4.Models;
using WebApplication4.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace WebApplication4.ViewModels
{
    public class PostViewModel
    {
        public int PostId { get; set; }
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        public string Title { get; set; }
        public ICollection<ReplyDto> Replies { get; set; }
        public bool CanEdit { get; set; }

        [Required]
        [StringLength(1000, MinimumLength =1)]
        public string Text { get; set; }

        public PostViewModel(Post post, ClaimsPrincipal user)
        {
            PostId = post.Id;
            TopicId = post.TopicId;
            TopicName = post.Topic.Name;
            Title = post.Title;
            Replies = post.Replies.Select(x => new ReplyDto
            {
                Id = x.Id,
                Text = x.Text,
                CreatedTime = x.CreatedTime,
                EditTime = x.EditTime,
                Author = x.Author,
                CanEdit = user.IsInRole("admin") || user.Identity.Name == x.Author.UserName
            }).ToList();
            CanEdit = user.IsInRole("admin") || user.Identity.Name == post.Author.UserName;
        }
    }

    public class ReplyDto
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime EditTime { get; set; }
        public IdentityUser Author { get; set; }
        public bool CanEdit { get; set; }

    }
}

WebApplication4/Controllers/PostsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Data;
using WebApplication4.Models;
using WebApplication4.ViewModels;

namespace WebApplication4.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public PostsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(x => x.Topic)
                .Include(x => x.Author)
                .Include(x => x.Replies)
                .ThenInclude(x => x.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            var model = new PostViewModel(post, User);

            return View(model);
        }

        // GET: Posts/Create
        public IActionResult Create(int topicId)
        {
            var topic = _context.Topics.Find(topicId);

            if (topic == null)
            {
                return NotFound();
            }

            var post = new PostCreateModel
            {
                TopicId = topicId,
                TopicName = topic.Name
            };

            return View(post);
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,CreatedTime,TopicId")] PostCreateModel model)
        {
            if (ModelState.IsValid)
            {
                var topic = _context.Topics.Find(model.TopicId);

                if (topic == null)
                {
                    return NotFound();
                }

                var DateTimeNow = DateTime.Now;
                var user = await _userManager.FindByNameAsync(User.Identity.Name);

                var post = new Post
                {
                    TopicId = topic.Id,
                    Title = model.Title,
                    Author = user,
                    CreatedTime = DateTimeNow,
                    Replies = new List<Reply>
                    {
                        new Reply
                        {
                            Text = model.Text,
                            Author = user,
                            CreatedTime= DateTimeNow,
                            EditTime = DateTimeNow,
                        }
                    }
                };

                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(TopicsController.Details), new { id = topic.Id, controller = "Topics"});
            }
            return View(model);
        }


        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .Include(p => p.Topic)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            
            if (!User.IsInRole("admin") && User.Identity.Name != post.Author.UserName)
            {
                return Forbid();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);

            if (!User.IsInRole("admin") && User.Identity.Name != post.Author.UserName)
            {
                return Forbid();
            }

            var topicId = post.TopicId;
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(TopicsController.Details), new { id = topicId, controller = "Topics" });
        }
    }
}

WebApplication4/Controllers/RepliesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    [Authorize]
    public class RepliesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public RepliesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: Replies/Create
        [HttpGet]
        public IActionResult Create()
        {
            return RedirectToAction(nameof(TopicsController.Index), new { Controller = "Topics"});
        }

        // POST: Replies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Text,PostId")] Reply reply)
        {
            if (ModelState.IsValid)
            {
                var DateTimeNow = DateTime.Now;
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                _context.Add(reply);

                reply.CreatedTime = DateTimeNow;
                reply.EditTime = DateTimeNow;
                reply.Author = user;

                _context.Add(reply);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(PostsController.Details), new { id = reply.PostId, controller = "Posts" });
        }

        // GET: Replies/Edit/5
        public IActionResult Edit(int? id)
        {
            return RedirectToAction(nameof(TopicsController.Index), new { controller = "Topics" });
        }

        // POST: Replies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Reply reply)
        {
            var newText = reply.Text;
            reply = _context.Replies.Find(reply.Id);
            
            if (reply == null)
            {
                return NotFound();
            }

            var postId = reply.PostId;

            if (ModelState.IsValid && reply.Text != newText)
            {
                reply.Text = newText;
                reply.EditTime = DateTime.Now;
                _context.Update(reply);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(PostsController.Details), new { id = postId, controller = "Posts" });
        }
    }
}

WebApplication4/Views/Posts/Create.cshtml
@model WebApplication4.ViewModels.PostCreateModel

@{
    ViewData["Title"] = "Create";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Topics" asp-action="Index">Topics</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Topics" asp-action="Details" asp-route-id="@Model.TopicId">@Model.TopicName</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Create new post</li>
    </ol>
</nav>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" asp-for="TopicId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <textarea asp-for="Text" class="form-control"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication4/Views/Posts/Delete.cshtml
@model WebApplication4.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Topics" asp-action="Index">Topics</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Topics" asp-action="Details" asp-route-id="@Model.Topic.Id">@Model.Topic.Name</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Posts" asp-action="Details" asp-route-id="@Model.Id">@Model.Title</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Delete post</li>
    </ol>
</nav>

<hr />
<h3>Are you sure you want to delete this post?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

WebApplication4/Views/Posts/Details.cshtml
@model WebApplication4.ViewModels.PostViewModel

@{
    ViewData["Title"] = Model.Title;
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-controller="Topics" asp-action="Index">Topics</a>
        </li>
        <li class="breadcrumb-item">
            <a asp-controller="Topics" asp-action="Details" asp-route-id="@Model.TopicId">@Model.TopicName</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">@Model.Title</li>
    </ol>
</nav>

<div class="d-flex justify-content-end mb-3">
    @if (Model.CanEdit)
    {
        <a class="ml-2 btn btn-outline-danger" asp-action="Delete" asp-route-id="@Model.PostId">
            <i class="bi bi-trash"></i>
            Delete topic
        </a>
    }
</div>

<hr />

@foreach (var reply in Model.Replies)
{
    var collapseId = $"collapseReply{reply.Id}";
    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between">
            <div>
                <span class="badge badge-dark">@reply.Author.UserName</span> at @reply.CreatedTime
            </div>
            <div>
                @if (reply.CanEdit)
                {
                <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#editModal"
                        onclick="InitEditModal('@reply.Id', '@reply.Text')">
                    <i class="bi bi-pencil"></i>
                    Edit
                </button>
                }
            </div>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <span>@reply.Text</span>
                @if (reply.CreatedTime != reply.EditTime)
                {
                    <footer class="blockquote-footer">edited at @reply.EditTime</footer>
                }
            </blockquote>
        </div>
        <div class="card-footer p-2">
            <a data-toggle="collapse" href="#@collapseId" role="button" aria-expanded="false">
                <i class="bi bi-reply"></i>
                Reply
            </a>
        </div>
    </div>

    <div class="collapse mb-4" id="@collapseId" data-parent="body">
        <div class="card border-primary">
            <div class="card-header">
                <span>Reply</span>
            </div>
            <div class="card-body">
                <form asp-controller="Replies" asp-action="Create" method="post">
                    @Html.AntiForgeryToken()
                    <input asp-for="@Model.PostId" type="hidden" />
                    <div class="form-group">
                        <label asp-for="Text" class="control-label"></label>
                        <textarea asp-for="Text" class="form-control"></textarea>
                        <span asp-validation-for="Text" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-0">
                        <input type="submit" value="Reply" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form asp-controller="Replies" asp-action="Edit" method="post">
            <input id="editId" type="hidden" name="id" value="0" />
            @Html.AntiForgeryToken()
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit reply</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Text" class="control-label"></label>
                        <textarea id="editText" asp-for="Text" class="form-control"></textarea>
                        <span asp-validation-for="Text" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    function InitEditModal(Id, Text) {
        document.getElementById('editId').value = Id;
        document.getElementById('editText').innerHTML = Text;
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}