WebApplication4/Models/Folder.cs
using System;

namespace WebApplication4.Models
{
    public class Folder
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Folder Parent { get; set; }
        public int? ParentId { get; set; }
    }
}

WebApplication4/ViewModels/FolderViewModel.cs
using System;
using System.Collections.Generic;
using WebApplication4.Models;
using WebApplication4.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using System.Linq;

namespace WebApplication4.ViewModels
{
    public class FolderViewModel
    {
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public List<Folder> Parents { get; set; }
        public List<Folder> SubFolders { get; set; }
        public List<ImageFile> Images { get; set; }

        [Required(ErrorMessage = "Please select a file")]
        [DataType(DataType.Upload)]
        public IFormFile Image { get; set; }

        public FolderViewModel(Folder folder, ApplicationDbContext context)
        {
            Id = folder.Id;
            ParentId = folder.ParentId;
            Name = folder.Name;
            Parents = new List<Folder>();

            GetParents(folder, context);
            GetImages(folder, context);
            GetSubFolders(folder, context);
        }

        private void GetParents(Folder folder, ApplicationDbContext context)
        {
            var parent = context.Folders.Find(folder.ParentId);

            if (parent != null)
            {
                GetParents(parent, context);
                Parents.Add(parent);
            }
        }

        private void GetImages(Folder folder, ApplicationDbContext context)
        {
            Images = context.ImageFiles.Where(x => x.FolderId == folder.Id).ToList();
        }

        private void GetSubFolders(Folder folder, ApplicationDbContext context)
        {
            SubFolders = context.Folders.Where(x => x.ParentId == folder.Id).ToList();
        }
    }
}

WebApplication4/Controllers/FoldersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Data;
using WebApplication4.Models;
using WebApplication4.ViewModels;

namespace WebApplication4.Controllers
{
    public class FoldersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoldersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Folders/Details/5
        public async Task<IActionResult> Details(int id = 1)
        {
            var folder = await _context.Folders
                .FirstOrDefaultAsync(m => m.Id == id);

            if (folder == null)
            {
                folder = await _context.Folders
                .FirstOrDefaultAsync(m => m.Id == 1);
            }

            var model = new FolderViewModel(folder, _context);

            return View(model);
        }

        // POST: Folders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ParentId")] Folder folder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(folder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(FoldersController.Details), new { id = folder.Id });
            }

            return RedirectToAction(nameof(FoldersController.Details), new { id = folder.ParentId });
        }

        // GET: Folders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 1)
            {
                return NotFound();
            }

            var folder = await _context.Folders.FindAsync(id);
            if (folder == null)
            {
                return NotFound();
            }

            return View(folder);
        }

        // POST: Folders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ParentId")] Folder folder)
        {
            if (id != folder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(folder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FolderExists(folder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = folder.Id });
            }
            return View(folder);
        }

        // GET: Folders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 1)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.Parent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (folder == null)
            {
                return NotFound();
            }

            return View(folder);
        }

        // POST: Folders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == 1)
            {
                return NotFound();
            }

            var folder = await _context.Folders.FindAsync(id);
            _context.Folders.Remove(folder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = folder.ParentId });
        }

        private bool FolderExists(int id)
        {
            return _context.Folders.Any(e => e.Id == id);
        }
    }
}

WebApplication4/Controllers/ImageFilesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Data;
using WebApplication4.Models;
using WebApplication4.ViewModels;

namespace WebApplication4.Controllers
{
    public class ImageFilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _HostEnvironment;

        public ImageFilesController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _HostEnvironment = hostEnvironment;
        }

        // GET: ImageFiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var imageFile = await _context.ImageFiles
                .Include(i => i.Folder)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (imageFile == null)
            {
                return NotFound();
            }

            var model = new ImageFileViewModel(imageFile, _context);

            return View(model);
        }

        // POST: ImageFiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile image, int folderId)
        {
            if (image != null && image.ContentType.StartsWith("image"))
            {
                //путь к папке
                string path = "/Files/" + image.FileName;
                //схраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_HostEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await image.CopyToAsync(fileStream);
                }

                ImageFile file = new ImageFile { Name = image.FileName, Path = path, FolderId = folderId };
                await _context.ImageFiles.AddAsync(file);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(FoldersController.Details), new { id = folderId, Controller = "Folders" });
        }

        // GET: ImageFiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var imageFile = await _context.ImageFiles
                .Include(i => i.Folder)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (imageFile == null)
            {
                return NotFound();
            }

            return View(imageFile);
        }

        // POST: ImageFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var imageFile = await _context.ImageFiles.FindAsync(id);
            _context.ImageFiles.Remove(imageFile);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(FoldersController.Details), new { id = imageFile.FolderId, Controller = "Folder"});
        }
    }
}

WebApplication4/Views/Folders/Delete.cshtml
@model WebApplication4.Models.Folder

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-route-id="@Model.Id">Back to List</a>
    </form>
</div>

WebApplication4/Views/Folders/Details.cshtml
@model WebApplication4.ViewModels.FolderViewModel

@{
    ViewData["Title"] = "Details";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        @foreach (var f in Model.Parents)
        {
            <li class="breadcrumb-item"><a asp-action="Details" asp-route-id="@f.Id">@f.Name</a></li>
        }
        <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
    </ol>
</nav>

<div class="d-flex mb-3">
    <a class="btn btn-outline-primary" href="#CreateFolderCollapse" data-toggle="collapse" role="button">
        <i class="bi bi-folder-plus"></i>
        Create new folder
    </a>
    @if (Model.Id != 1)
    {
        <a class="ml-2 btn btn-outline-secondary" asp-action="Edit" asp-route-id="@Model.Id">
            <i class="bi bi-pencil"></i>
            Edit folder
        </a>
    }
    <a class="ml-2 btn btn-outline-success" href="#AddImageCollapse" data-toggle="collapse" role="button">
        <i class="bi bi-file-earmark-plus"></i>
        Add image
    </a>
    @if (Model.Id != 1 && !Model.Images.Any() && !Model.SubFolders.Any())
    {
        <a class="ml-2 btn btn-outline-danger" asp-action="Delete" asp-route-id="@Model.Id">
            <i class="bi bi-trash"></i>
            Delete folder
        </a>
    }
</div>

<div class="collapse mb-3" id="CreateFolderCollapse" data-parent="body">
    <div class="card border-primary">
        <div class="card-header">
            <span>Create new folder</span>
        </div>
        <div class="card-body">
            <form asp-controller="Folders" asp-action="Create" method="post">
                @Html.AntiForgeryToken()
                <input name="ParentId" value="@Model.Id" type="hidden" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input type="text" name="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group mb-0">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div class="collapse mb-3" id="AddImageCollapse" data-parent="body">
    <div class="card border-primary">
        <div class="card-header">
            <span>Add new image</span>
        </div>
        <div class="card-body">
            <form asp-controller="ImageFiles" asp-action="Create" method="post" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                <input name="folderId" value="@Model.Id" type="hidden" />
                <div class="form-group">
                    <input asp-for="Image" class="form-control-file" accept="image/*" onchange="validateFileType(this)"/>
                    <span id="FileValidationSpan" asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group mb-0">
                    <input type="submit" value="Add" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<table class="table table-striped">
    <tbody>
        @if (Model.ParentId != null)
        {
            <tr>
                <td>
                    <a class="card-body" asp-action="Details" asp-route-id="@Model.ParentId">
                        <i class="bi bi-folder2-open"></i>
                        ..
                    </a>
                </td>
            </tr>
        }
        @foreach (var f in Model.SubFolders)
        {
            <tr>
                <td>
                    <a class="card-body" asp-action="Details" asp-route-id="@f.Id">
                        <i class="bi bi-folder"></i>
                        @f.Name
                    </a>
                </td>
            </tr>
        }
        @foreach (var f in Model.Images)
        {
            <tr>
                <td>
                    <a class="card-body" asp-controller="ImageFiles" asp-action="Details" asp-route-id="@f.Id">
                        <i class="bi bi-file-image"></i>
                        @f.Name
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    function validateFileType(file) {
        var fileName = file.value;
        var idxDot = fileName.lastIndexOf(".") + 1;
        var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
        if (!(extFile == "jpg" || extFile == "jpeg" || extFile == "png")) {
            document.getElementById("FileValidationSpan").innerHTML = "Only jpg/jpeg and png files are allowed!";
        }
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication4/Views/Folders/Edit.cshtml
@model WebApplication4.Models.Folder

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Folder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ParentId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.Id">Back to file system</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}